### ISSUE TITLE
Process names are getting too long for syslog

### ISSUE THREAD

**Issue by sarahhodne** [travis-ci/terraform-config#137]
We're currently having some process names be too long for syslog, so things like `travis-worker-production-com-xserve-1` get truncated to `travis-worker-production-com-xse`. One option is to change `-production-` to `-prod-`.

@igorwwwwwwwwwwwwwwwwwwww I see you changed `prod` to `production` in cfa00dd1558061113d8dfe941973d3a3c2bed366, would you be against changing it back to `prod` to shorten the names?

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
@henrikhodne I have no concerns with changing it back to `prod`. 👍

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
Do we know where the limit is being applied? Is it in rsyslog itself? Or in papertrail?

If it's rsyslog, then it might also be worth investigating extending the tag length beyond 32 bytes:

* http://www.rsyslog.com/sende-messages-with-tags-larger-than-32-characters/
* https://www.sysorchestra.com/2014/07/28/modifying-rsyslog-syslogtag-length-limit/

**Comment by henrikhodne** [comment]
I couldn't find anywhere that Papertrail truncates this, I suspect it's just rsyslog. Worth a shot, I guess.
