### ISSUE TITLE
Worker instance bootstrap time improvements: EBS volumes option

### ISSUE THREAD

**Issue by soulshake** [travis-ci/terraform-config#246]
I'm evaluating options for speeding up the instance bootstrap time; one option is to pre-seed the Docker images on the instance, so they only have to be updated at runtime instead of pulled fresh from Docker Hub.

My work in progress is here: https://github.com/travis-infrastructure/terraform-config/pull/245

### TL;DR

I've attached an EBS volume at `/mnt` on a normal instance (having disabled direct LVM), restarted travis-worker to repull the images, then detached that volume (which now contains 10GB+ of Docker images) and created a snapshot out of it. However, using the snapshot to create volumes on _other_ instances doesn't work.

### Details

In order to test this approach, I create two instances in my ASG, **A** and **B**.

On instance A:
- `/etc/docker/daemon.json` contains the line `"graph": "/mnt/docker"`
- `/etc/default/travis-worker-cloud-init` contains the line `export TRAVIS_DOCKER_DISABLE_DIRECT_LVM=true`
- I `stop docker`
- I `umount /mnt`
- I attach an EBS volume to the instance at `/dev/xvdx`
- I run `mkfs -t ext3 /dev/xvdx`
- I mount the device at /mnt (`mount /dev/xvdx /mnt -o _netdev`)
- I `start docker` and `restart travis-worker` which causes it to download a bunch of images (this takes about 10 minutes)
- I `docker pull alpine` and verify that I can run containers
- I `stop docker`
- I `umount /mnt`
- I detach the volume from the instance via the AWS console

Now, if I reattach that same volume to the same instance, everything works great. If I instead attach it instance B and mount it in the same way, I get the docker upstart logs show that Docker fails to start:

`Error starting daemon: error initializing graphdriver: devmapper: Base Device UUID and Filesystem verification failed: devicemapper: Error running deviceCreate (ActivateDevice) dm_task_run failed`

That (`Base Device UUID and Filesystem verification failed`) seems pretty self-explanatory: the volume was created on a different instance. But I'm not sure how to handle it.

Also, when I try to `dockerd --debug`, I get this:
```
[...]
DEBU[0001] Golang's threads limit set to 108000         
DEBU[0001] devicemapper: driver version is 4.35.0       
DEBU[0001] devmapper: Generated prefix: docker-202:6144-5193738 
DEBU[0001] devmapper: Checking for existence of the pool docker-202:6144-5193738-pool 
DEBU[0001] devmapper: poolDataMajMin=253:1 poolMetaMajMin=253:0
DEBU[0001] devmapper: Failed to open file /mnt/docker/951968.951968/devicemapper/devicemapper/data 
DEBU[0001] devmapper: Failed to load thin pool loopback device information:open /mnt/docker/951968.951968/devicemapper/devicemapper/data: no such file or directory 
ERRO[0001] [graphdriver] prior storage driver devicemapper failed: open /mnt/docker/951968.951968/devicemapper/devicemapper/data: no such file or directory 
DEBU[0001] Cleaning up old mountid : start.             
Error starting daemon: error initializing graphdriver: open /mnt/docker/951968.951968/devicemapper/devicemapper/data: no such file or directory
```

Suggestions welcome! In the meantime I'll do some reading about `devicemapper` and thin pools today.

**Comment by soulshake** [comment]
@meatballhat I noted that you suggested "disabling direct LVM"

Based on what I've just read ([[1](https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/#configure-direct-lvm-mode-for-production)]), I think maybe what you meant by "disable direct lvm" was "just let docker use its direct lvm defaults (`/etc/docker/daemon.json`) instead of doing it ourselves (`/etc/docker/daemon-direct-lvm.json`), can you confirm?

**Comment by meatballhat** [comment]
@soulshake my understanding is that the default settings in `/etc/docker/daemon.json` do not use direct LVM.  The critical difference is in the storage-opts settings that specify `datadev` and `metadatadev`. 👍

**Comment by edmorley** [comment]
Hope you don't mind the drive-by (and apologies if I've misunderstood the proposed change), but we tried the "create EBS volume from snapshot" approach for pre-seeding the source checkout on our Firefox build instances - and ran into some performance issues due to using the same volume for heavy writes:
https://bugzilla.mozilla.org/show_bug.cgi?id=1305174

Anyway, it's possible the top-up `docker pull` after instance start might not be write-heavy enough to run into the same issue (in our case we were using the restored EBS volume for boot/scratch too, which you may not be) - but thought I should mention it in case it saved you the same confusion it did us :-)

**Comment by soulshake** [comment]
@edmorley That's quite interesting, thanks for sharing. Out of curiosity, what was your approach for automating the "create EBS volume from snapshot" approach? I ran into a speedbump trying this with Terraform, then ended up setting the whole thing aside because other things came up.

We're hoping to do some benchmarks in the next few weeks to compare various configurations. Feel free to chime in anytime!

**Comment by edmorley** [comment]
> Out of curiosity, what was your approach for automating the creation of an EBS volume snapshot?

Ah so "we" was a bit of a royal we, I'm on a different team but saw the linked ticket fly by a while back and followed the discussion/debugging attempts there since it tickled my curiosity. I believe they use a combination of a home-grown boto solution, topped up with some cloudformation and terraform (because why not use them all? 😆 - albeit the repo is 5+ years old, so pre-dates the existence of terraform):
https://github.com/mozilla-releng/build-cloud-tools
