### ISSUE TITLE
Worker v.3.4.0 rollout

### ISSUE THREAD

**Issue by soulshake** [travis-ci/terraform-config#292]
Tracking issue for rolling out https://github.com/travis-infrastructure/terraform-config/pull/291

- [x] gce-staging-1
- [x] gce-production-1
- [x] gce-production-2
- [x] gce-production-4
- [x] gce-production-5
- [x] aws-staging-1
- [x] aws-production-2
- [x] macstadium-shared-1
- [x] macstadium-shared-2

**Comment by meatballhat** [comment]
:sparkling_heart:
