### ISSUE TITLE
Migrate GCE to use cloud-config.yml a la AWS

### ISSUE THREAD

**Issue by meatballhat** [travis-ci/terraform-config#46]
Including:
- making sure the module load order is the same as AWS
- making sure the user generation per-instance scripts run correctly so that SSH access is possible via per-user accounts instead of `ubuntu` user

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
Might be looking into this as part of https://github.com/travis-pro/team-blue/issues/454.

**Comment by meatballhat** [comment]
Totes done!
